services:
  grafana:
    image: grafana/grafana-oss
    scale: 1
    deploy:
      mode: global
    restart: unless-stopped
    volumes:
      - type: volume
        source: grafana-storage
        target: /var/lib/grafana
    ports:
      - name: grafana_http
        protocol: tcp
        app_protocol: http
        published: 4000
        target: 3000
    networks:
      gateway-metric:
      gateway-monitor:

  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    volumes:
      - type: bind
        source: prometheus
        target: /etc/prometheus
        read_only: true
      - type: volume
        source: prometheus-data
        target: /prometheus
    expose:
      - 9090
    depends_on:
      - anubis
    networks:
      gateway-metric:

  anubis:
    build: anubis
    restart: unless-stopped
    environment:
      SERVE_ROBOTS_TXT: "true"
      TARGET: http://nginx:8080
      POLICY_FNAME: /data/cfg/botPolicy.yaml
      OG_PASSTHROUGH: "true"
      OG_EXPIRY_TIME: 24h
    volumes:
      - type: bind
        source: anubis
        target: /data/cfg
        read_only: true
    expose:
      - 8923
      - 9090
    networks:
      gateway-public:
      gateway-metric:

  nginx-prometheus:
    image: nginx/nginx-prometheus-exporter
    restart: unless-stopped
    command:
      - "--nginx.scrape-uri=http://nginx:9090"
    expose:
      - 9113
    networks:
      gateway-metric:

  nginx:
    image: nginx
    restart: unless-stopped
    dns:
      - "1.1.1.1"
      - "1.0.0.1"
    volumes:
      - type: bind
        source: nginx
        target: /etc/nginx/conf.d
        read_only: true
      - type: bind
        source: tls/server
        target: /etc/nginx/tls
        read_only: true
      - type: bind
        source: public
        target: /var/www
        read_only: true
    ports:
      - name: gateway_https
        protocol: tcp
        app_protocol: https
        published: 12345
        target: 443
    expose:
      - 8080
      - 9090
    networks:
      gateway-public:
        ipv4_address: 172.172.172.172
      gateway-metric:

  dlulu:
    build:
      context: dlulu
    environment:
      UL_DIR: /data/ul
      DL_DIR: /data/dl
      SECKEY_FILE: /data/seckey
      ACCESSKEY_FILE: /data/accesskey
      ADMINKEY_FILE: /data/adminkey
      BASEURL: /dlulu
    expose:
      - 9075
    user: "1000"
    networks:
      gateway-public:
    volumes:
      - type: bind
        source: dlulu/ul
        target: /data/ul
      - type: bind
        source: dlulu/dl
        target: /data/dl
        read_only: true
      - type: bind
        source: dlulu-sec.key.txt
        target: /data/seckey
        read_only: true
      - type: bind
        source: dlulu-access.key.txt
        target: /data/accesskey
        read_only: true
      - type: bind
        source: dlulu-admin.key.txt
        target: /data/adminkey
        read_only: true

  bored:
    build:
      context: bored
    environment:
      SECKEY_FILE: /data/seckey
      ADMINKEY_FILE: /data/adminkey
      BASEURL: /bored
      DB_PATH: /data/bored.db
    expose:
      - 8510
    networks:
      gateway-public:
    volumes:
      - type: volume
        source: bored-data
        target: /data
      - type: bind
        source: bored-sec.key.txt
        target: /data/seckey
        read_only: true
      - type: bind
        source: bored-admin.key.txt
        target: /data/adminkey
        read_only: true

networks:
  gateway-public:
    name: gateway-public
    ipam:
      config:
        - subnet: 172.172.172.0/24
          gateway: 172.172.172.1
  gateway-metric:
    name: gateway-metric
    internal: true
  gateway-monitor:

volumes:
  grafana-storage:
  prometheus-data:
  bored-data:
