server {
  listen 443 ssl;
  listen [::]:443 ssl;
  include conf.d/name.inc;
  http2 on;

  include conf.d/client.inc;
  include conf.d/gzip.inc;
  include conf.d/header.inc;
  include conf.d/tls.inc;

  port_in_redirect off;
  server_name_in_redirect off;
  error_page 497 301 =307 https://$host:12345$request_uri;

  location / {
    proxy_pass http://anubis:8923;
    proxy_set_header X-Http-Version $server_protocol;
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Connection "";
    proxy_buffering off;
    proxy_request_buffering off;
    proxy_http_version 1.1;
  }
}

# server {
#   listen 443 ssl;
#   server_name invidious.nerdvpn.de;
#   http2 on;
#   include conf.d/tls.inc;
#
#   location / {
#     proxy_pass https://invidious.nerdvpn.de;
# proxy_buffering off;
# proxy_request_buffering off;
# proxy_http_version 1.1;
#   }
# }

server {
  listen 8080;
  server_name nginx;

  include conf.d/client.inc;

  location /dlulu {
    proxy_pass http://dlulu:9075;
    proxy_set_header Host $http_host;
    proxy_set_header Connection "";
    proxy_buffering off;
    proxy_request_buffering off;
    proxy_http_version 1.1;
  }

  location /bored/ {
    proxy_pass http://bored:8510/;
    proxy_set_header Host $http_host;
    proxy_set_header Connection "";
    proxy_buffering off;
    proxy_request_buffering off;
    proxy_http_version 1.1;
  }

  location /bored {
    return 301 https://$host:12345/bored/;
  }

  location /git/ {
    proxy_pass http://gitea:3000/;
    proxy_set_header Host $http_host;
    proxy_set_header Connection "";
    proxy_buffering off;
    proxy_request_buffering off;
    proxy_http_version 1.1;
  }

  location /git {
    return 301 https://$host:12345/git/;
  }

  root "/var/www";
  index index.html;
}

server {
  listen 9090;
  server_name nginx;

  stub_status;
}
