server {
  listen 443 ssl;
  listen [::]:443 ssl;
  server_name localhost 127.0.0.1 192.168.1.2 esdmr.iddns.ir "";
  http2 on;

  include conf.d/client.inc;
  include conf.d/gzip.inc;
  include conf.d/header.inc;
  include conf.d/tls.inc;

  port_in_redirect off;
  server_name_in_redirect off;
  error_page 497 301 =307 https://$host:9443$request_uri;

  location / {
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Http-Version $server_protocol;
    proxy_pass http://anubis:8923;
  }
}

server {
  listen 8080;
  server_name nginx;

  root "/var/www";
  index index.html;
}

server {
  listen 9090;
  server_name nginx;

  stub_status;
}
